project_id = "ymckdnwlrbnbcsffmivw"

[functions.github-remix]
verify_jwt = false

[functions.create-pix]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.remix-queue]
verify_jwt = false

[functions.lookup-cpf]
verify_jwt = false
